apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-prod

resources:
- ../../base
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: blog-backend
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: blog-frontend

commonLabels:
  environment: prod