apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohammadrezachegini/fullstack-gitops-argocd
    targetRevision: master
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true